name: deploy-manifests
on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #step -get doctl + authenticate
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}

      #step - get kubernetes config and save it inside container
      # doctl kubernetes cluster kubeconfig save <name of kubernetes cluster>
      - run: doctl kubernetes cluster kubeconfig save ticketing
            
      #step - apply the configuration files from infra/k8s into cluster
      - run: kubectl apply -f infra/k8s
