name: tests-orders

on: 
  pull_request:
    paths: 
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Install pnpm
        run: npm install -g pnpm

      - name: checkout code
        uses: actions/checkout/@v2
      
      - name: install and run orders tests
        run: cd orders && pnpm i && pnpm run test:ci
